### ISSUE TITLE
Spelling error in Functions.md

### ISSUE THREAD

**Issue by wally-rblx** [0x90-NOP/Lua#1]
```
funtion add(x, y)
  product = x + y
  return product 
  
  --[[
    you can replace "product" with x + y, so you don't create a variable
    but, we'll keep it consistent.
  ]]
end
```

should be
```
function add(x, y)
  product = x + y
  return product 
  
  --[[
    you can replace "product" with x + y, so you don't create a variable
    but, we'll keep it consistent.
  ]]
end
```

Notice **funtion** should be spelled as **function**.

**Comment by Scarperino** [comment]
You have a very big issue that I've noticed.
it's called being retarded, fix it please

**Comment by 0x90-NOP** [comment]
> 
> 
> You're not going to talk about the clear lack of use of localization?
> 
>     1. Performance.
> 
>     2. A bit more client-security.
> 
> 
> Elaborations:
> 
>     1. Accessing the stack is faster than GETGLOBAL (which also has to grab the func name from the const pool and then access its associated element in the _ENV table.)
> 
>     2. It is much harder to externally access localized functions than global functions, as you have to rely on hooks / upvalues.

that's obviously something that i'm going to cover, like i said: this is not finished.
