### ISSUE TITLE
More info & conclusion needed in Conditional Statements.md

### ISSUE THREAD

**Issue by ClassyInori** [0x90-NOP/Lua#2]
```Lua
hungry = true
if hungry then -- we don't need (== true)
  print("You are hungry")
else
  print("You are not hungry")
end
```

Not enough information as to what TEST vs EQ does.
EQ (A == B)
TEST (Val ~= nil and Val ~= false)

Also no info on stacking conditions, e.g. 
```Lua
if A == B and C then...
```

Also, yeah, you're missing your 'conclusion' thing.

**Comment by Scarperino** [comment]
+1 because this person is sexy

**Comment by 0x90-NOP** [comment]
> 
> 
> ```lua
> hungry = true
> if hungry then -- we don't need (== true)
>   print("You are hungry")
> else
>   print("You are not hungry")
> end
> ```
> 
> Not enough information as to what TEST vs EQ does.
> EQ (A == B)
> TEST (Val ~= nil and Val ~= false)
> 
> Also no info on stacking conditions, e.g.
> 
> ```lua
> if A == B and C then...
> ```
> 
> Also, yeah, you're missing your 'conclusion' thing.

conditional statements isn't finished
